apiVersion: v1
kind: Namespace
metadata:
  name: testing

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-web
  namespace: testing
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: simple-web
  template:
    metadata:
      labels:
        k8s-app: simple-web
    spec:
      containers:
      - name: simple-web
        image: yeasy/simple-web:latest
        ports:
          - name: http-port
            containerPort: 80
    
---

apiVersion: v1
kind: Service
metadata:
  name: simple-web
  namespace : testing
spec:
  ports:
    - name: tcp-6080-80
      protocol: TCP
      port: 6080
      targetPort: 80
      nodePort: 31570
  selector:
    k8s-app: simple-web
  type: LoadBalancer
  sessionAffinity: None
  externalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  allocateLoadBalancerNodePorts: true
  internalTrafficPolicy: Cluster

